### ISSUE TITLE
Pinpoint render duplicated

### ISSUE THREAD

**Issue by samwang0723** [Lienchi/GoGaming#61]
![screen shot 2018-04-12 at 1 46 28 pm](https://user-images.githubusercontent.com/538559/38658529-2c8c781c-3e58-11e8-964c-365d6b2333ea.png)

When I clicked the pinpoint it shows duplicated icon on the map.

**Comment by anna770822** [comment]
@samwang0723 
checking on current location marker setting

**Comment by Lienchi** [comment]
Lienchi@ba4fd6c31a2d072dfda996430c21881592a527c1 fixed this issue, thanks
